"""Agent Framework protocol -- decouples agent logic from training infrastructure.

Inspired by ROLL's three-layer separation (Training Framework / Agent Framework /
Sandbox Manager), this module defines the structural contracts that let agent
logic implementations remain completely unaware of Monarch, distributed training,
or weight synchronization.

Key types:

- ``AgentLogic``   -- protocol for pluggable agent strategies (ReAct, CoT, ...)
- ``AgentAction``  -- what an agent step produces (response text + tool calls)
- ``ToolCall``     -- a single tool invocation request
- ``ToolResult``   -- the outcome of executing a tool call
- ``GenerationResult`` -- LLM output with RL-relevant metadata (logprobs, version)
- ``AgentContext`` -- read-only view of available services for agent logic

This module has ZERO external dependencies (no torch, no transformers, no monarch).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Protocol, runtime_checkable

# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class ToolCall:
    """A single tool invocation requested by the agent.

    Attributes:
        type: Tool identifier (e.g. ``"code_execution"``, ``"web_search"``).
        content: Payload for the tool (source code, query string, etc.).
        metadata: Optional extra data for the tool.
    """

    type: str
    content: str
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class ToolResult:
    """Outcome of executing a ``ToolCall``.

    Attributes:
        success: Whether the tool executed without errors.
        output: The tool's stdout / return value.
        error: Error message if ``success`` is False.
        tool_call: The original request that produced this result.
    """

    success: bool
    output: str = ""
    error: str = ""
    tool_call: ToolCall | None = None


@dataclass
class GenerationResult:
    """LLM generation output with RL training metadata.

    The ``text`` field is all an ``AgentLogic`` needs.  The remaining
    fields are collected by ``AgentActor`` for training data assembly
    and are opaque to agent logic implementations.

    Attributes:
        text: Generated text.
        token_ids: Output token IDs (for training).
        logprobs: Per-token log-probabilities (for PPO/GRPO advantage).
        version: Generator weight version at generation time.
        raw: Full upstream response dict (preserved for adapters).
    """

    text: str = ""
    token_ids: list[int] = field(default_factory=list)
    logprobs: list[float] = field(default_factory=list)
    version: int = -1
    raw: dict[str, Any] = field(default_factory=dict)


@dataclass
class AgentAction:
    """Output of a single agent reasoning step.

    Attributes:
        response: The model's textual response for this turn.
        tool_calls: Tool invocations extracted from the response.
        done: If True, the agent considers the episode finished.
        metadata: Arbitrary data the agent logic wants to carry forward.
    """

    response: str = ""
    tool_calls: list[ToolCall] = field(default_factory=list)
    done: bool = False
    metadata: dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Protocols
# ---------------------------------------------------------------------------


@runtime_checkable
class AgentLogic(Protocol):
    """Pluggable agent strategy -- pure logic, no infrastructure awareness.

    Implementations define *what* the agent does (extract tools, decide
    when to stop, format feedback) while ``AgentActor`` handles *how*
    (call Generator via ModelProxy, execute tools, collect training data).

    Lifecycle per episode::

        for each turn:
            gen_result = model_proxy.generate(messages)
            action     = agent.process_response(gen_result.text, messages)
            ...execute tools...
            feedback   = agent.format_feedback(action, tool_results, reward)
            if action.done or not agent.should_continue(turn, reward):
                break
            messages += [assistant_msg, user_feedback]

    Built-in implementations:
        - ``forge.agents.react.SimpleReActAgent``   (code-execution ReAct loop)
    """

    def process_response(
        self,
        response: str,
        messages: list[dict[str, str]],
    ) -> AgentAction:
        """Analyse a generation response and decide what to do.

        Typical work: extract code blocks / tool-use tags, check for
        a final answer marker, populate ``AgentAction.tool_calls``.

        Args:
            response: The raw text generated by the LLM.
            messages: Full conversation history up to (but not including)
                      this response.

        Returns:
            An ``AgentAction`` describing extracted tool calls and
            whether the episode is considered finished.
        """
        ...

    def should_continue(self, turn: int, reward: float) -> bool:
        """Decide whether to proceed to the next turn.

        Called *after* tool execution and reward computation.

        Args:
            turn: Zero-based turn index just completed.
            reward: Reward received for this turn.

        Returns:
            ``True`` to continue, ``False`` to end the episode.
        """
        ...

    def format_feedback(
        self,
        action: AgentAction,
        tool_results: list[ToolResult],
        reward: float,
    ) -> str:
        """Build the user-feedback message appended before the next turn.

        Args:
            action: The agent's action for this turn.
            tool_results: Outcomes of any tool calls.
            reward: Reward for this turn.

        Returns:
            A feedback string to include as the next user message.
        """
        ...
